# Generated by Django 3.1.6 on 2021-02-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_data',
            name='gene',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
