# Generated by Django 3.1.6 on 2021-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextseq_metrics',
            name='bases_Q30',
            field=models.FloatField(db_column='percentage_bases_>Q30'),
        ),
        migrations.AlterField(
            model_name='nextseq_metrics',
            name='clusters_PF',
            field=models.FloatField(db_column='percentage_clusters_PF'),
        ),
    ]
