# Generated by Django 3.1.6 on 2021-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20210313_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextseq_metrics',
            name='Notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
